import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import MobileNav from "@/components/MobileNav";
const IRANSansX = localFont({
  src: [
    { path: "../../public/fonts/IRANSansX-Light.woff2", weight: "300" },
    { path: "../../public/fonts/IRANSansX-Regular.woff2", weight: "400" },
    { path: "../../public/fonts/IRANSansX-Medium.woff2", weight: "500" },
    { path: "../../public/fonts/IRANSansX-DemiBold.woff2", weight: "600" },
    { path: "../../public/fonts/IRANSansX-Bold.woff2", weight: "700" },
    { path: "../../public/fonts/IRANSansX-Black.woff2", weight: "900" },
  ],
  variable: "--font-IRANSansX",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0", // تنظیم viewport
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='fa' dir='rtl'>
      <body className={`${IRANSansX.className} pb-[45px]`}>
        <Header />
        {children}
        <MobileNav />
      </body>
    </html>
  );
}
